#!/bin/sh
#
# @name SIH Quadplane VTOL
#
# @type Standard VTOL
# @class VTOL
#
# @maintainer
#
# @output MAIN1 motor 1
# @output MAIN2 motor 2
# @output MAIN3 motor 3
# @output MAIN4 motor 4
# @output AUX1 Aileron 1
# @output AUX2 Aileron 2
# @output AUX3 Elevator
# @output AUX4 Rudder
# @output AUX5 Throttle
#

sh /etc/init.d/rc.vtol_defaults

if [ $AUTOCNF = yes ]
then
    #companion communication 
	#param set FW_AIRSPD_MAX 25
	#param set FW_AIRSPD_MIN 0
	#param set FW_AIRSPD_TRIM 0
	#param set FW_THR_IDLE 0
	#param set FW_T_HRATE_FF 0
	#param set FW_T_HRATE_P 0.01
	#param set FW_T_INTEG_GAIN 0
	#param set FW_T_PTCH_DAMP 0.2
	#param set FW_T_RLL2THR 10
	#param set FW_T_SPDWEIGHT 0.1
	#param set FW_T_SRATE_P 0.3
	#param set FW_T_THRO_CONST 1.0
	#param set FW_T_TIME_CONST 1.0

	#param set LND_FLIGHT_T_HI 1
	#param set LND_FLIGHT_T_LO -1

	#param set MC_DTERM_CUTOFF 30
	param set MC_ROLLRATE_P 3.5
	param set MC_ROLLRATE_I 0.05
	param set MC_ROLLRATE_D 0.01
	param set MC_ROLLRATE_MAX 120
	param set MC_PITCHRATE_P 2.0
	param set MC_PITCHRATE_I 0.05
	param set MC_PITCHRATE_D 0.005
	param set MC_PITCHRATE_MAX 120
	param set MC_YAWRATE_P 0.8
	param set MC_YAWRATE_I 0.05
	param set MC_YAWRATE_D 0.0
	param set MC_YAWRATE_MAX 120
	param set MC_ROLL_P 8.0
	param set MC_PITCH_P 6.5
    param set MC_YAW_P 2.8
	#param set MC_PR_INT_LIM 0.1

	#param set MIS_LTRMIN_ALT 10
	#param set MIS_TAKEOFF_ALT 10
	#param set MIS_YAW_TMT 10

	#param set MPC_ACC_HOR_MAX 2
	#param set MPC_ACC_HOR 2
	#param set MPC_THR_MIN 0
	#param set MPC_TKO_SPEED 1
	#param set MPC_TILTMAX_AIR 35
	#param set MPC_XY_P 0
	#param set MPC_Z_P 1.0
	#param set MPC_XY_VEL_P 0.05
	#param set MPC_XY_VEL_I 0.007
	#param set MPC_XY_VEL_D 0.005
    param set MPC_XY_VEL_MAX 25
	#param set MPC_XY_CRUISE 25
	param set MPC_VEL_MANUAL 25
	#param set MPC_XY_TRAJ_P 0
	#param set MPC_Z_VEL_MAX_DN 1.5
	#param set MPC_Z_VEL_P 0.5
	#param set MPC_Z_VEL_I 0.05
	#param set MPC_Z_VEL_D 0.0
    #param set MPC_MAN_XY_EXPO 0.0
    #param set MPC_MAN_YAW_EXPO 0.0

	#param set NAV_ACC_RAD 5
	#param set NAV_LOITER_RAD 80

    param set WV_EN 0

	#param set VT_F_TRANS_DUR 1.5
	#param set VT_F_TRANS_THR 0.75
	#param set VT_TILT_FW 3.1415
	#param set VT_TILT_TRANS 1.2
	#param set VT_ELEV_MC_LOCK 0
	#param set VT_TYPE 1
    #param set PWM_RATE 400
	#param set VT_TYPE 2
	#param set VT_MOT_ID 1234
	#param set VT_FW_MOT_OFFID 1234
fi

# was 22
set MAV_TYPE 21

set MIXER tiltrotor
set MIXER_AUX tiltrotor

# set MIXER quad_x
# set MIXER_AUX vtol_AAERT

set PWM_OUT 12345678

# set SYS_HITL to 2 to start the SIH and avoid sensors startup
param set SYS_HITL 2
